apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gneerl04o-go
  janus-idp.io/tekton: gneerl04o-go
  backstage.io/kubernetes-id: gneerl04o-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gneerl04o-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
