apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gneerl04o-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gneerl04o-go 
  name: gneerl04o-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gneerl04o-go 
